package loan_issue;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class issue_ind_loan extends javax.swing.JFrame {

    /**
     * Creates new form issue_ind_loan
     */
    public issue_ind_loan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        transtype = new javax.swing.JTextField();
        memid = new javax.swing.JTextField();
        amt = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sharecontr = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ISSUE INDIVIDUAL LOAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transaction Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 100, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Share Contribution");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loan Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 100, -1));

        transtype.setForeground(new java.awt.Color(0, 0, 0));
        transtype.setText("LN1");
        getContentPane().add(transtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 100, -1));

        memid.setForeground(new java.awt.Color(0, 0, 0));
        memid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memidFocusLost(evt);
            }
        });
        getContentPane().add(memid, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 100, -1));

        amt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 100, -1));

        date.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 100, -1));

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ISSUE LOAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, -1, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 99, 99, -1));

        name1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 100, 22));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Member Name");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 100, -1));

        sharecontr.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(sharecontr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 100, 22));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcimage.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try
        {
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");
        
        String insert="INSERT INTO trans_main(trans_type,trans_date,mem_id,trans_amount)VALUES(?,?,?,?)";
        PreparedStatement pstmt= conn.prepareStatement(insert);
                pstmt.setString(1,transtype.getText());
                
                SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date udt=sdf1.parse(date.getText());
                long ms=udt.getTime();
                java.sql.Date sqdt=new java.sql.Date(ms);
                pstmt.setDate(2,sqdt);
                
                pstmt.setInt(3,Integer.parseInt(memid.getText()) );
                
   
                pstmt.setInt(4,-(Integer.parseInt(amt.getText()))); 
                
                if(Integer.parseInt(amt.getText())<=(Integer.parseInt(sharecontr.getText())))
                {
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Insert successful");
                }
                else
                {
                JOptionPane.showMessageDialog(null,"Unable to borrow more than three times the share contribution");
                }
                
                 
                

        }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void memidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memidFocusLost
        // TODO add your handling code here:
        
        
         try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
            String name="select mem_name from mem_reg where mem_id = ?";
            PreparedStatement pstmt3= conn.prepareStatement(name);
            pstmt3.setInt(1,Integer.parseInt(memid.getText()));
            
            ResultSet resultset = pstmt3.executeQuery();
                   
              
               if(resultset.next()==false)
                        {
                                JOptionPane.showMessageDialog(null,"Member does not exist");
                        }
                else
                        {
                                do
                                {
                                    name1.setText(resultset.getString("mem_name"));
                                }
                                while(resultset.next());
                        }
                                    
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         
          try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
           String shares="select*from trans_main where mem_id =? and trans_type=?";
                 PreparedStatement pstmt2= conn.prepareStatement(shares);
                 pstmt2.setInt(1,Integer.parseInt(memid.getText()));
                 pstmt2.setString(2,"MCTRB");
                 
                 ResultSet resultset = pstmt2.executeQuery();
                 
                 
                  int z = 0;
                  while(resultset.next())   
        {
                
                int x=resultset.getInt("trans_amount");
                z=z+x;
                
        }
                  
                  
                 String loan="select*from trans_main where mem_id =? and trans_type=?";
                 PreparedStatement pstmt3= conn.prepareStatement(loan);
                 pstmt3.setInt(1,Integer.parseInt(memid.getText()));
                 pstmt3.setString(2,"LN1");
                 
                 ResultSet resultset2 = pstmt3.executeQuery();
                 
                 
                  int l = 0;
                  while(resultset2.next())   
        {
                int x=resultset2.getInt("trans_amount");
                l=l+x; 
        }
       
                  int limit=(3*z)+l;
                  sharecontr.setText(Integer.toString(limit));
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_memidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue_ind_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue_ind_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue_ind_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue_ind_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue_ind_loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JTextField date;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memid;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel sharecontr;
    private javax.swing.JTextField transtype;
    // End of variables declaration//GEN-END:variables
}
