package loan_issue;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
public class issue_grp_loan extends javax.swing.JFrame {

    public issue_grp_loan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        date = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        transtype = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        amt = new javax.swing.JTextField();
        grpid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        grpname = new javax.swing.JLabel();
        sharecontr = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("ISSUE LOAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        date.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 100, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Share Contribution");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, 22));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Loan Amount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 100, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 100, -1));

        transtype.setForeground(new java.awt.Color(0, 0, 0));
        transtype.setText("LN1");
        getContentPane().add(transtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 100, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ISSUE GROUP LOAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Group ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transaction Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        amt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 100, -1));

        grpid.setForeground(new java.awt.Color(0, 0, 0));
        grpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                grpidFocusLost(evt);
            }
        });
        getContentPane().add(grpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 100, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Group Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 89, -1));

        grpname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(grpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 100, 22));

        sharecontr.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(sharecontr, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 100, 22));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcimage.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

            String insert="INSERT INTO trans_main(trans_type,trans_date,grp_id,trans_amount)VALUES(?,?,?,?)";
            PreparedStatement pstmt= conn.prepareStatement(insert);
            pstmt.setString(1,transtype.getText());

            SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date udt=sdf1.parse(date.getText());
            long ms=udt.getTime();
            java.sql.Date sqdt=new java.sql.Date(ms);
            pstmt.setDate(2,sqdt);

            
            pstmt.setInt(3,Integer.parseInt(grpid.getText()) );

           

            pstmt.setInt(4,-(Integer.parseInt(amt.getText())));

            if(Integer.parseInt(amt.getText())<=(Integer.parseInt(sharecontr.getText())))
            {
                pstmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Insert successful");
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Unable to borrow more than three times the share contribution");
            }

        }

        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void grpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grpidFocusLost
        // TODO add your handling code here:
        //GETTING GROUP NAME!!!!!!!!!!!!!!!!
        try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
            String name="select grp_name from grp_reg where grp_id = ?";
            PreparedStatement pstmt3= conn.prepareStatement(name);
            pstmt3.setInt(1,Integer.parseInt(grpid.getText()));
            
            ResultSet resultset = pstmt3.executeQuery();
                   
              
               if(resultset.next()==false)
                        {
                                JOptionPane.showMessageDialog(null,"Group does not exist");
                        }
                else
                        {
                                do
                                {
                                    grpname.setText(resultset.getString("grp_name"));
                                }
                                while(resultset.next());
                        }
                                    
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         
        
        //GETTING SHARE CONTRIBUTION!!!!!!!!!!!!!
            try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
           String shares="select*from trans_main where mem_id is null and grp_id=? and trans_type=?";
                 PreparedStatement pstmt2= conn.prepareStatement(shares);
                 pstmt2.setInt(1,Integer.parseInt(grpid.getText()));
                 pstmt2.setString(2,"MCTRB");
                 
                 ResultSet resultset = pstmt2.executeQuery();
                 
                 
                  int z = 0;
                  while(resultset.next())   
        {
                
                int x=resultset.getInt("trans_amount");
                z=z+x;
                
        }
                  
                  
                 String loan="select*from trans_main where mem_id is null and grp_id=? and trans_type=?";
                 PreparedStatement pstmt3= conn.prepareStatement(loan);
                 pstmt3.setInt(1,Integer.parseInt(grpid.getText()));
                 pstmt3.setString(2,"LN1");
                 
                 ResultSet resultset2 = pstmt3.executeQuery();
                 
                 
                  int l = 0;
                  while(resultset2.next())   
        {
                int x=resultset2.getInt("trans_amount");
                l=l+x; 
        }
       
                  int limit=(3*z)+l;
                  sharecontr.setText(Integer.toString(limit));
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_grpidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(issue_grp_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(issue_grp_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(issue_grp_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(issue_grp_loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new issue_grp_loan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JTextField date;
    private javax.swing.JTextField grpid;
    private javax.swing.JLabel grpname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel sharecontr;
    private javax.swing.JTextField transtype;
    // End of variables declaration//GEN-END:variables
}
