package loan_issue;

import loan_repayment.pay_grp_loan;
import loan_repayment.pay_grpmem_loan;
import java.sql.*;
import loan_repayment.ind_loan_repayment;

public class loan_form extends javax.swing.JFrame {

    /**
     * Creates new form loan_form
     */
    public loan_form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        issloan = new javax.swing.JRadioButton();
        payloan = new javax.swing.JRadioButton();
        isstype = new javax.swing.JComboBox<>();
        paytype = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(issloan);
        issloan.setForeground(new java.awt.Color(255, 255, 255));
        issloan.setText("Issue Loan");
        getContentPane().add(issloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        buttonGroup1.add(payloan);
        payloan.setForeground(new java.awt.Color(255, 255, 255));
        payloan.setText("Repay Loan");
        getContentPane().add(payloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        isstype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIVIDUAL LOAN", "GROUP MEMBER LOAN", "GROUP LOAN" }));
        getContentPane().add(isstype, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        paytype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIVIDUAL LOAN", "GROUP MEMBER LOAN", "GROUP LOAN" }));
        getContentPane().add(paytype, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcimage.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
             //1.initialise connection
        Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");
        
        
        //LOAN ISUUE!!!!!
        
        
        if((issloan.isSelected()) && (isstype.getSelectedItem().toString()== "INDIVIDUAL LOAN"))
        {
              dispose();
                    issue_ind_loan x = new issue_ind_loan();
                    x.show();
            
        }
        
        else if ((issloan.isSelected()) && (isstype.getSelectedItem().toString()== "GROUP MEMBER LOAN"))
        {
             dispose();
                    issue_grpmem_loan x = new issue_grpmem_loan();
                    x.show();
           
        }
        else if ((issloan.isSelected()) && (isstype.getSelectedItem().toString()== "GROUP LOAN"))
        {
             dispose();
                    issue_grp_loan x = new issue_grp_loan();
                    x.show();
           
        }
        
        
        //LOAN REPAYMENT!!!!!
        
        if((payloan.isSelected()) && (paytype.getSelectedItem().toString()== "INDIVIDUAL LOAN"))
        {
              dispose();
                    ind_loan_repayment x = new ind_loan_repayment();
                    x.show();
            
        }
        
        else if ((payloan.isSelected()) && (paytype.getSelectedItem().toString()== "GROUP MEMBER LOAN"))
        {
             dispose();
                    pay_grpmem_loan x = new pay_grpmem_loan();
                    x.show();
           
        }
        else if ((payloan.isSelected()) && (paytype.getSelectedItem().toString()== "GROUP LOAN"))
        {
             dispose();
                    pay_grp_loan x = new pay_grp_loan();
                    x.show();
           
        }
             

        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loan_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loan_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton issloan;
    private javax.swing.JComboBox<String> isstype;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton payloan;
    private javax.swing.JComboBox<String> paytype;
    // End of variables declaration//GEN-END:variables
}
