package monthly_contribution;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  

public class group_contr extends javax.swing.JFrame {

    /**
     * Creates new form monthly_contributions
     */
    public group_contr() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        transtype = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        memid = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        amt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        memname = new javax.swing.JLabel();
        grpid = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GROUP MONTHLY CONTRIBUTIONS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Group ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, 22));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transaction Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        transtype.setForeground(new java.awt.Color(0, 0, 0));
        transtype.setText("MCTRB");
        getContentPane().add(transtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 150, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Member ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        memid.setForeground(new java.awt.Color(0, 0, 0));
        memid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memidFocusLost(evt);
            }
        });
        getContentPane().add(memid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 150, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("FINISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 333, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Date");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        date.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 150, -1));

        amt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 150, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, 22));

        memname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(memname, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 150, 22));

        grpid.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(grpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 150, 22));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcimage.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try
        {
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");
        
        //MEMBER CONTRIBUTION!!!
        String mem1="INSERT INTO trans_main(trans_type,trans_date,mem_id,grp_id,trans_amount)VALUES(?,?,?,?,?)";
        PreparedStatement pstmt= conn.prepareStatement(mem1);
        
        
        pstmt.setString(1,transtype.getText());
          
        SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date udt=sdf1.parse(date.getText());
        long ms=udt.getTime();
        java.sql.Date sqdt=new java.sql.Date(ms);
        pstmt.setDate(2,sqdt);
        
        pstmt.setInt(3,Integer.parseInt(memid.getText()));
        pstmt.setInt(4,Integer.parseInt(grpid.getText()));
        pstmt.setInt(5,Integer.parseInt(amt.getText())-200);
        
        //GROUP CONTRIBUTION 
        
        String grpcontr1 ="INSERT INTO trans_main(trans_type,trans_date,grp_id,trans_amount)VALUES(?,?,?,200)";
        PreparedStatement pstmt2= conn.prepareStatement(grpcontr1);
        
       
        pstmt2.setString(1,transtype.getText());
          
        pstmt2.setDate(2,sqdt);
       
        pstmt2.setInt(3,Integer.parseInt(grpid.getText()));
     
       
        
                if(Integer.parseInt(amt.getText())>=1000)
                {
              pstmt.executeUpdate();
              pstmt2.executeUpdate();
    
              JOptionPane.showMessageDialog(null,"Insert successful");
              
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Monthly contribution less than minimum threshold");
                }
 
         }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void memidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memidFocusLost
        // TODO add your handling code here:
        
        
        
         try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
            String name="select * from mem_reg where mem_id = ?";
            PreparedStatement pstmt3= conn.prepareStatement(name);
            pstmt3.setInt(1,Integer.parseInt(memid.getText()));
            
            ResultSet resultset = pstmt3.executeQuery();
                   
              
               if(resultset.next()==false)
                        {
                                JOptionPane.showMessageDialog(null,"Member does not exist");
                        }
                else
                        {
                                do
                                {
                                    memname.setText(resultset.getString("mem_name"));
                                    int x= resultset.getInt("grp_id");
                                    grpid.setText(Integer.toString(x));
                                }
                                while(resultset.next());
                        }
                                    
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_memidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(group_contr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(group_contr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(group_contr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(group_contr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new group_contr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JTextField date;
    private javax.swing.JLabel grpid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField memid;
    private javax.swing.JLabel memname;
    private javax.swing.JTextField transtype;
    // End of variables declaration//GEN-END:variables
}
