package loan_repayment;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  
import java.util.concurrent.TimeUnit;
public class ind_loan_repayment extends javax.swing.JFrame {

    /**
     * Creates new form template1
     */
    public ind_loan_repayment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        transtype = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        memid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        memname = new javax.swing.JLabel();
        amtborr = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        intgained = new javax.swing.JLabel();
        intpaid = new javax.swing.JLabel();
        princpaid = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        amt.setForeground(new java.awt.Color(0, 0, 0));
        amt.setPreferredSize(new java.awt.Dimension(0, 22));
        amt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                amtFocusLost(evt);
            }
        });
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 355, 150, 27));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date Repaid");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 400, 127, 27));

        d2.setForeground(new java.awt.Color(0, 0, 0));
        d2.setPreferredSize(new java.awt.Dimension(0, 22));
        d2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                d2FocusLost(evt);
            }
        });
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 400, 150, 27));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Member ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 130, 127, 27));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transaction Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 85, 127, 27));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Member Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 175, 127, 27));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INDIVIDUAL LOAN REPAYMENT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 38, -1, -1));

        transtype.setForeground(new java.awt.Color(0, 0, 0));
        transtype.setText("LN2");
        transtype.setPreferredSize(new java.awt.Dimension(0, 22));
        transtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transtypeActionPerformed(evt);
            }
        });
        getContentPane().add(transtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 85, 150, 27));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount Repaid");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 355, 127, 27));

        memid.setForeground(new java.awt.Color(0, 0, 0));
        memid.setPreferredSize(new java.awt.Dimension(0, 22));
        memid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                memidFocusLost(evt);
            }
        });
        getContentPane().add(memid, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 130, 150, 27));

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("FINISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 509, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Interest Gained");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 310, 127, 27));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Interest Paid");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 445, 127, 27));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Principal Paid");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 487, 127, 27));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Loan Amount Borrowed");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 220, -1, 27));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date Borrowed");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 265, 104, 27));

        memname.setForeground(new java.awt.Color(255, 255, 255));
        memname.setPreferredSize(new java.awt.Dimension(0, 22));
        getContentPane().add(memname, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 175, 150, 27));

        amtborr.setForeground(new java.awt.Color(255, 255, 255));
        amtborr.setPreferredSize(new java.awt.Dimension(0, 22));
        getContentPane().add(amtborr, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 220, 150, 27));

        d1.setForeground(new java.awt.Color(255, 255, 255));
        d1.setPreferredSize(new java.awt.Dimension(0, 22));
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 265, 150, 27));

        intgained.setForeground(new java.awt.Color(255, 255, 255));
        intgained.setPreferredSize(new java.awt.Dimension(0, 22));
        getContentPane().add(intgained, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 310, 150, 27));

        intpaid.setForeground(new java.awt.Color(255, 255, 255));
        intpaid.setPreferredSize(new java.awt.Dimension(0, 22));
        getContentPane().add(intpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 445, 150, 27));

        princpaid.setForeground(new java.awt.Color(255, 255, 255));
        princpaid.setPreferredSize(new java.awt.Dimension(0, 22));
        getContentPane().add(princpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 484, 150, 27));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loan_repayment/JDBC2.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void transtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transtypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

          
            String insert="INSERT INTO trans_main(trans_type,trans_date,mem_id,trans_amount)VALUES(?,?,?,?)";
            PreparedStatement pstmt= conn.prepareStatement(insert);

            pstmt.setString(1,transtype.getText());

            SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date udt=sdf1.parse(d2.getText());
            long ms=udt.getTime();
            java.sql.Date sqdt=new java.sql.Date(ms);
            pstmt.setDate(2,sqdt);

            pstmt.setInt(3,Integer.parseInt(memid.getText()));
            
            pstmt.setDouble(4, Double.parseDouble(princpaid.getText()));

            pstmt.executeUpdate();


//INTEREST!!!!!
            String interest ="INSERT INTO trans_main(trans_type,trans_date,mem_id,trans_amount)VALUES(?,?,?,?)";
            PreparedStatement pstmt2= conn.prepareStatement(interest);

            pstmt2.setString(1,"INT");//INTEREST

            pstmt2.setDate(2,sqdt);

            pstmt2.setInt(3,Integer.parseInt(memid.getText()));
            
            pstmt2.setDouble(4,Double.parseDouble(intpaid.getText()));

                pstmt2.executeUpdate();
                JOptionPane.showMessageDialog(null,"Insert successful");

            

        }

        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void memidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memidFocusLost
        // TODO add your handling code here:
        
        
        //MEMBER NAME!!!!!!!!!!!!
         try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
            String name="select mem_name from mem_reg where mem_id = ?";
            PreparedStatement pstmt2= conn.prepareStatement(name);
            pstmt2.setInt(1,Integer.parseInt(memid.getText()));
            
            ResultSet resultset = pstmt2.executeQuery();
                   
              
               if(resultset.next()==false)
                        {
                                JOptionPane.showMessageDialog(null,"Member does not exist");
                        }
                else
                        {
                                do
                                {
                                    memname.setText(resultset.getString("mem_name"));
                                }
                                while(resultset.next());
                        }
                                    
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
         
         //LOAN AMOUNT BORROWED!!!!!!
         
          try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
           String shares="select*from trans_main where mem_id =? and trans_type=?";
                 PreparedStatement pstmt3= conn.prepareStatement(shares);
                 pstmt3.setInt(1,Integer.parseInt(memid.getText()));
                 pstmt3.setString(2,"LN1");
                 ResultSet resultset = pstmt3.executeQuery();
                 
                 
                  int z = 0;
                  while(resultset.next())   
        {
      
                int x=-(resultset.getInt("trans_amount"));
                z=z+x;
                String y=Integer.toString(z);
                amtborr.setText(y);
        }
       
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
          
          
          //DATE BORROWED!!!!!!!!!!!!
          
            try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");
               
        String shares="select*from trans_main where mem_id =? and trans_type=?";
                 PreparedStatement pstmt4= conn.prepareStatement(shares);
                 pstmt4.setInt(1,Integer.parseInt(memid.getText()));
                 pstmt4.setString(2,"LN1");
                 ResultSet resultset = pstmt4.executeQuery();
                   
              
               if(resultset.next()==false)
                        {
                                JOptionPane.showMessageDialog(null,"Member does not exist or no loan balance");
                        }
                else
                        {
                                do
                                {
                                  
                                     Date d3=(resultset.getDate("trans_date"));
                                     String d=d3.toString();
                                     d1.setText(d);
                                } 
                                while(resultset.next());
                        }
                }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        
         
        
    }//GEN-LAST:event_memidFocusLost

    private void d2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_d2FocusLost
        // TODO add your handling code here:
        
         //INTEREST GAINED!!!!!!
          
           try
        {
         
        
        
            SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date d5=sdf1.parse(d2.getText());
            
            SimpleDateFormat sdf2=new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date d4=sdf2.parse(d1.getText());
            
            long diffInMillies = Math.abs(d5.getTime() - d4.getTime());
            long diff = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);
            
            /*String g=Long.toString(diff);
            JOptionPane.showMessageDialog(null,g);*/
            if(diff<=1095)
            {
            int i=Integer.parseInt(amtborr.getText());
            double rate=0.144;
            
            double gained= i * rate * (diff/365);
            String g=Double.toString(gained);
            
            intgained.setText(g);
            }
            else
            { 
                JOptionPane.showMessageDialog(null,"Loan Repayment Period Has Exceeded 3 years");
            }
            
            
    
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
  
    }//GEN-LAST:event_d2FocusLost

    private void amtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amtFocusLost
        // TODO add your handling code here:
        
          
           //INTEREST AND PRINCIPAL PAID!!!!!!!!!!
           
           
           int portions=Integer.parseInt(amt.getText());
            double intpaid2= portions*(14.4/114.4);
            double princpaid2= portions*(100/114.4);
            
            intpaid.setText(Double.toString(intpaid2));
            princpaid.setText(Double.toString(princpaid2));
            
  
    }//GEN-LAST:event_amtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ind_loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ind_loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ind_loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ind_loan_repayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ind_loan_repayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JLabel amtborr;
    private javax.swing.JLabel d1;
    private javax.swing.JTextField d2;
    private javax.swing.JLabel intgained;
    private javax.swing.JLabel intpaid;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField memid;
    private javax.swing.JLabel memname;
    private javax.swing.JLabel princpaid;
    private javax.swing.JTextField transtype;
    // End of variables declaration//GEN-END:variables
}
