package registration;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;  
public class grpreg_fees extends javax.swing.JFrame {

    
    public grpreg_fees() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        transtype = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        grpid = new javax.swing.JTextField();
        amt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        grpname = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        date.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 171, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Transaction Type");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        transtype.setForeground(new java.awt.Color(0, 0, 0));
        transtype.setText("REG");
        transtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transtypeActionPerformed(evt);
            }
        });
        getContentPane().add(transtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 171, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GROUP REGISTRATION FEES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Group ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Group Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Amount:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        grpid.setForeground(new java.awt.Color(0, 0, 0));
        grpid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                grpidFocusLost(evt);
            }
        });
        grpid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grpidActionPerformed(evt);
            }
        });
        getContentPane().add(grpid, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 171, -1));

        amt.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 171, -1));

        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("FINISH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        grpname.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(grpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 171, 16));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcimage.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         try
        {
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");
        
        String insert="INSERT INTO trans_main(trans_type,trans_date,grp_id,trans_amount)VALUES(?,?,?,?)";
        
        PreparedStatement pstmt= conn.prepareStatement(insert);
        

        pstmt.setString(1,transtype.getText());
        
        
        SimpleDateFormat sdf1=new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date udt=sdf1.parse(date.getText());
        long ms=udt.getTime();
        java.sql.Date sqdt=new java.sql.Date(ms);
        pstmt.setDate(2,sqdt);
        
        pstmt.setInt(3,Integer.parseInt(grpid.getText()));
        pstmt.setInt(4,Integer.parseInt(amt.getText()));
        
                if(Integer.parseInt(amt.getText())>=5000)
                {
              pstmt.executeUpdate();
              JOptionPane.showMessageDialog(null,"insert successful");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"registration failed....insufficient registration fees...try again");
                }
                
         }
        
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void grpidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grpidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_grpidActionPerformed

    private void transtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transtypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transtypeActionPerformed

    private void grpidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grpidFocusLost
        // TODO add your handling code here:
        
        try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
            String name="select grp_name from grp_reg where grp_id = ?";
            PreparedStatement pstmt3= conn.prepareStatement(name);
            pstmt3.setInt(1,Integer.parseInt(grpid.getText()));
            
            ResultSet resultset = pstmt3.executeQuery();
                   
              
               if(resultset.next()==false)
                        {
                                JOptionPane.showMessageDialog(null,"Group does not exist");
                        }
                else
                        {
                                do
                                {
                                    grpname.setText(resultset.getString("grp_name"));
                                }
                                while(resultset.next());
                        }
                                    
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_grpidFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grpreg_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grpreg_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grpreg_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grpreg_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grpreg_fees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amt;
    private javax.swing.JTextField date;
    private javax.swing.JTextField grpid;
    private javax.swing.JLabel grpname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField transtype;
    // End of variables declaration//GEN-END:variables
}
