import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import registration.member_registration;
import registration.group_registration;


public class start_page extends javax.swing.JFrame {

    /**
     * Creates new form start_page
     */
    public start_page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        memreg = new javax.swing.JRadioButton();
        grpreg = new javax.swing.JRadioButton();
        nxtbtn = new javax.swing.JButton();
        trans = new javax.swing.JRadioButton();
        orgincome = new javax.swing.JRadioButton();
        div = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE AN OPTION");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 175, -1));

        buttonGroup1.add(memreg);
        memreg.setForeground(new java.awt.Color(255, 255, 255));
        memreg.setText("MEMBER REGISTRATION");
        getContentPane().add(memreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        buttonGroup1.add(grpreg);
        grpreg.setForeground(new java.awt.Color(255, 255, 255));
        grpreg.setText("GROUP REGISTRATION");
        getContentPane().add(grpreg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 170, -1));

        nxtbtn.setText("NEXT");
        nxtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nxtbtnActionPerformed(evt);
            }
        });
        getContentPane().add(nxtbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 75, -1));

        buttonGroup1.add(trans);
        trans.setForeground(new java.awt.Color(255, 255, 255));
        trans.setText("MAKE A TRANSACTION");
        getContentPane().add(trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 190, -1));

        buttonGroup1.add(orgincome);
        orgincome.setForeground(new java.awt.Color(255, 255, 255));
        orgincome.setText("COMPUTE ORGANISATION'S INCOME");
        orgincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgincomeActionPerformed(evt);
            }
        });
        getContentPane().add(orgincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 252, -1));

        buttonGroup1.add(div);
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("COMPUTE DIVIDENDS TO SHAREHOLDERS");
        getContentPane().add(div, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel2.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MWANZO BARAKA MANAGEMENT INFORMATION SYSTEM");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 560, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcimage.jpg"))); // NOI18N
        jLabel4.setText("j");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nxtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nxtbtnActionPerformed
        // TODO add your handling code here:
        

        if (memreg.isSelected())
                {
                    dispose();
                    member_registration x = new member_registration();
                    x.setVisible(true);
                }
        else if(grpreg.isSelected())
        {
            dispose();
            group_registration y = new group_registration();
            y.show();
        }
        else if(trans.isSelected())
        {
            dispose();
            make_transaction z = new make_transaction();
            z.show();
            
        }
        else if(orgincome.isSelected())
        {
             try
        {
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/mwanzo","Muchiri","Muchiri1234!");

           
           String income= "select*from trans_main where trans_type =? or trans_type=?";
                 PreparedStatement pstmt2= conn.prepareStatement(income);
                 
                 pstmt2.setString(1,"INT");
                 pstmt2.setString(2,"PEN");
                 ResultSet resultset = pstmt2.executeQuery();
                 
                 
                  int z = 0;
                  while(resultset.next())   
        {
                
                int x=resultset.getInt("trans_amount");
                z=z+x;
                
        }
                       JOptionPane.showMessageDialog(null,"Total Income for the Organisation="+z);

            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        }
        
        else if(div.isSelected())
        {
            dispose();
            dividends_form z = new dividends_form();
            z.show();
            
        }
        
    }//GEN-LAST:event_nxtbtnActionPerformed

    private void orgincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orgincomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {                
                new start_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton div;
    private javax.swing.JRadioButton grpreg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton memreg;
    private javax.swing.JButton nxtbtn;
    private javax.swing.JRadioButton orgincome;
    private javax.swing.JRadioButton trans;
    // End of variables declaration//GEN-END:variables
}
